Repository CS2113-AY1819S1-T09-3/main, pull requests merged in 2018-10, with the labels that each got.

#25 Added: undoAll and redoAll
  docs/DeveloperGuide.adoc
  docs/images/UndoRedoExecuteRedoAllStateListDiagram.png
  docs/images/UndoRedoExecuteUndoAllStateListDiagram.png
  src/main/java/seedu/address/logic/commands/AddItemCommand.java
  src/main/java/seedu/address/logic/commands/RedoAllCommand.java
  src/main/java/seedu/address/logic/commands/UndoAllCommand.java
  src/main/java/seedu/address/logic/parser/AddItemCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
  src/main/java/seedu/address/model/item/Item.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.medium, severity.Medium, type.enhancement

#21 Developer guide changed
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/commands/EventCommand/AddEventCommand.java
Labels: priority.medium, type.enhancement, type.story

#26 Added: new UI.png
  docs/images/Ui.png
Labels: type.task

#29 Major UI updates
  src/main/java/seedu/address/commons/events/ui/LedgerPanelSelectionChangedEvent.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddLedgerCommand.java
  src/main/java/seedu/address/logic/commands/CreditCommand.java
  src/main/java/seedu/address/logic/commands/DebitCommand.java
  src/main/java/seedu/address/logic/commands/ledger/AddLedgerCommand.java
  src/main/java/seedu/address/logic/commands/ledger/CreditCommand.java
  src/main/java/seedu/address/logic/parser/AddLedgerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CreditCommandParser.java
  src/main/java/seedu/address/logic/parser/DebitCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ledger/AddLedgerCommandParser.java
  src/main/java/seedu/address/logic/parser/ledger/CreditCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/ledger/Account.java
  src/main/java/seedu/address/model/ledger/DateLedger.java
  src/main/java/seedu/address/model/ledger/Ledger.java
  src/main/java/seedu/address/model/ledger/UniqueLedgerList.java
  src/main/java/seedu/address/ui/LedgerCard.java
  src/main/java/seedu/address/ui/LedgerListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MainWindowBackup.java
  src/main/resources/view/LedgerListCard.fxml
  src/main/resources/view/LedgerListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MainWindow2Backup.fxml
  src/main/resources/view/MainWindowBackup.fxml
Labels: type.epic

#32 fixed the storage bug
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
Labels: priority.high

#36 Test Cases updated
  docs/DummySearchPage.html
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/AddMemberCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.medium

#40 UI for ItemList, reposense config, README.adoc changes
  .gitignore
  README.adoc
  _reposense/config.json
  config.json
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/commons/events/ui/ItemPanelSelectionChangedEvent.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddItemCommand.java
  src/main/java/seedu/address/logic/parser/AddItemCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/item/Item.java
  src/main/java/seedu/address/model/item/ItemName.java
  src/main/java/seedu/address/model/item/ItemQuantity.java
  src/main/java/seedu/address/model/item/UniqueItemList.java
  src/main/java/seedu/address/model/item/exceptions/DuplicateItemException.java
  src/main/java/seedu/address/ui/ItemCard.java
  src/main/java/seedu/address/ui/ItemListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/ItemListCard.fxml
  src/main/resources/view/ItemListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddItemCommandTest.java
  src/test/java/seedu/address/logic/commands/AddMemberCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.high, status.ongoing

#46 Update to credit and debit command after resolving ledger bug
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ledger/AddLedgerCommand.java
  src/main/java/seedu/address/logic/commands/ledger/CreditCommand.java
  src/main/java/seedu/address/logic/commands/ledger/DebitCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ledger/AddLedgerCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/ledger/Account.java
  src/main/java/seedu/address/model/ledger/DateLedger.java
  src/main/java/seedu/address/model/ledger/Ledger.java
  src/main/java/seedu/address/model/ledger/UniqueLedgerList.java
  src/main/java/seedu/address/model/ledger/exceptions/DuplicateLedgerException.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/LedgerListPanel.java
Labels: type.story

#41 Storage for Items
  README.adoc
  build.gradle
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddItemCommand.java
  src/main/java/seedu/address/logic/commands/DeleteItemCommand.java
  src/main/java/seedu/address/logic/commands/EditItemCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteItemCommandParser.java
  src/main/java/seedu/address/logic/parser/EditItemCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/item/Item.java
  src/main/java/seedu/address/storage/XmlAdaptedItem.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/main/java/seedu/address/ui/ItemCard.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.enhancement

#49 parseCommand bug corrections
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/RedoAllCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoAllCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/ledger/CreditCommand.java
  src/main/java/seedu/address/logic/commands/ledger/DebitCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddMemberCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: type.bug

#54 V1.3 bug fixes and doc update
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/ledger/CreditCommand.java
  src/main/java/seedu/address/logic/commands/ledger/DebitCommand.java
  src/main/java/seedu/address/model/ledger/Account.java
  src/main/java/seedu/address/model/ledger/Ledger.java
  src/main/java/seedu/address/model/ledger/UniqueLedgerList.java
Labels: type.bug, type.enhancement, type.task

#57 small UI changes
  src/main/java/seedu/address/logic/commands/ledger/CreditCommand.java
  src/main/java/seedu/address/logic/commands/ledger/DebitCommand.java
  src/main/java/seedu/address/model/ledger/Account.java
  src/main/java/seedu/address/ui/LedgerCard.java
  src/main/resources/view/LedgerListPanel.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.medium

#58 More updates on UG
  docs/UserGuide.adoc
Labels: type.enhancement

#50 clean-up (Daryl)
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/item/Item.java
Labels: type.task
